name: Continuous Deployment
on: push
jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo Hello There!
      - name: show ASCII greeting
        uses: mscoutermarsh/ascii-art-action@master
        with:
          text: 'HELLO!'
